### ISSUE TITLE
[Question] Why LESS mixins over extends?

### ISSUE THREAD

**Issue by JustMaier** [webcomm/magento-boilerplate#108]
I really like what you've done with the boilerplate. Making it work with the default views is brilliant and definitely makes sense for future development.

On thing I was wondering though as I looked through the LESS files was why you chose Mixins over [Extends](http://lesscss.org/features/#extend-feature-reducing-css-size)?

For example:
```less
.product-view .product-shop {
  &:extend(.panel all);
  padding: 15px;
  border-color: @panel-default-border;
}
```
Results in:
```css
.panel,
.product-view .product-shop {
  margin-bottom: 20px;
  background-color: #ffffff;
  border: 1px solid transparent;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
}
.product-view .product-shop {
  padding: 15px;
  border-color: #dddddd;
}
```

The difference is that you aren't repeating all of the CSS for the panel in every place that you might need to include it's styles.

I'm definitely not a LESS expert, so I was curious.
